# Generated by Django 4.2.11 on 2024-11-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customgroup_alter_roles_menu'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customgroup',
            managers=[
            ],
        ),
    ]
