# Generated by Django 4.2.11 on 2024-11-27 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_mykey_yourmodel_key_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mykey2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='key_name2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.mykey2'),
        ),
    ]
