# Generated by Django 4.2.11 on 2024-12-02 12:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('immarot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('active', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3, verbose_name='Active?')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('active', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3, verbose_name='Active?')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='projectlocation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='projectlocation',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='projectlocation',
            name='active',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3, verbose_name='Active?'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('active', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3, verbose_name='Active?')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Project Name')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('facing', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facing')),
                ('building_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Building Height (m)')),
                ('land_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Land Area (sq.m)')),
                ('project_launching_date', models.DateField(blank=True, null=True, verbose_name='Project Launching Date')),
                ('project_hand_over_date', models.DateField(blank=True, null=True, verbose_name='Project Hand Over Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('project_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immarot.projectlocation', verbose_name='Project Location')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('flat_type', models.CharField(max_length=255, verbose_name='Flat Type')),
                ('floor_number', models.IntegerField(verbose_name='Floor Number')),
                ('flat_size', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Flat Size (sq.m)')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Unit Price')),
                ('total_flat_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Flat Price')),
                ('car_parking_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Car Parking Charge')),
                ('utility_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Utility Charge')),
                ('additional_work_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Additional Work Charge')),
                ('other_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Other Charge')),
                ('deduction_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Deduction/Discount')),
                ('refund_additional_work_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Refund Additional Work Charge')),
                ('net_sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Net Sales (Flat) Price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Product Image')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='immarot.project', verbose_name='Project Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('title', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('assign_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('lead_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='immarot.leadsource')),
                ('lead_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='immarot.leadstatus')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='immarot.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
