# Generated by Django 4.2.11 on 2024-12-02 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immarot', '0003_alter_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('father_or_husband_name', models.CharField(max_length=255, verbose_name="Father's or Husband's Name")),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Customer Email')),
                ('mailing_address', models.TextField(verbose_name='Mailing Address')),
                ('nid', models.CharField(max_length=50, verbose_name='National ID (NID)')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
